/* eslint-disable no-unused-vars */
/**
 * GenerationResultDialog Component
 * Displays generation outcome
 * 
 * Location: src/components/packages/GenerationResultDialog.jsx
 */

import React from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Box,
  Typography,
  Grid,
  Chip,
  Button,
  Divider,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  Alert,
  Paper
} from '@mui/material';
import {
  CheckCircle as SuccessIcon,
  Error as ErrorIcon,
  Warning as WarningIcon,
  FileDownload as DownloadIcon,
  History as HistoryIcon,
  Dashboard as DashboardIcon
} from '@mui/icons-material';

const GenerationResultDialog = ({
  open,
  onClose,
  result,
  onViewPackages,
  onViewDownloads,
  onViewHistory,
  onGoToDashboard
}) => {
  if (!result) return null;

  const isSuccess = result.success !== false;
  const packageCount = result.packages?.length || 0;
  const failedCount = result.failed || 0;
  const warnings = result.warnings || [];

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="md"
      fullWidth
    >
      <DialogTitle>
        <Box display="flex" alignItems="center" gap={1}>
          {isSuccess ? (
            <SuccessIcon color="success" />
          ) : (
            <ErrorIcon color="error" />
          )}
          <Typography variant="h6">
            {isSuccess ? 'Generation Completed' : 'Generation Failed'}
          </Typography>
        </Box>
      </DialogTitle>

      <DialogContent>
        {/* Summary */}
        <Box sx={{ mb: 2 }}>
          <Grid container spacing={2}>
            <Grid item xs={4}>
              <Paper variant="outlined" sx={{ p: 2, textAlign: 'center' }}>
                <Typography variant="caption" color="text.secondary">
                  Packages Generated
                </Typography>
                <Typography variant="h5" color="success.main">
                  {packageCount}
                </Typography>
              </Paper>
            </Grid>
            <Grid item xs={4}>
              <Paper variant="outlined" sx={{ p: 2, textAlign: 'center' }}>
                <Typography variant="caption" color="text.secondary">
                  Failed
                </Typography>
                <Typography variant="h5" color="error.main">
                  {failedCount}
                </Typography>
              </Paper>
            </Grid>
            <Grid item xs={4}>
              <Paper variant="outlined" sx={{ p: 2, textAlign: 'center' }}>
                <Typography variant="caption" color="text.secondary">
                  Warnings
                </Typography>
                <Typography variant="h5" color="warning.main">
                  {warnings.length}
                </Typography>
              </Paper>
            </Grid>
          </Grid>
        </Box>

        {/* Details */}
        <Box sx={{ mb: 2 }}>
          <Typography variant="subtitle2" gutterBottom>
            Generation Details
          </Typography>
          <Grid container spacing={1}>
            <Grid item xs={6}>
              <Typography variant="caption" color="text.secondary">
                Version
              </Typography>
              <Typography variant="body2">
                {result.version || 'N/A'}
              </Typography>
            </Grid>
            <Grid item xs={6}>
              <Typography variant="caption" color="text.secondary">
                Generation Time
              </Typography>
              <Typography variant="body2">
                {result.generationTime 
                  ? `${Math.round(result.generationTime / 1000)}s`
                  : 'N/A'}
              </Typography>
            </Grid>
            <Grid item xs={12}>
              <Typography variant="caption" color="text.secondary">
                Generated By
              </Typography>
              <Typography variant="body2">
                {result.generatedBy?.name || result.generatedBy || 'System'}
              </Typography>
            </Grid>
          </Grid>
        </Box>

        {/* Warnings */}
        {warnings.length > 0 && (
          <Alert severity="warning" sx={{ mb: 2 }}>
            {warnings.length} warning(s) during generation
            <List dense>
              {warnings.map((warning, index) => (
                <ListItem key={index}>
                  <ListItemIcon>
                    <WarningIcon fontSize="small" color="warning" />
                  </ListItemIcon>
                  <ListItemText primary={warning} />
                </ListItem>
              ))}
            </List>
          </Alert>
        )}

        {/* Generated Packages */}
        {result.packages && result.packages.length > 0 && (
          <Box>
            <Typography variant="subtitle2" gutterBottom>
              Generated Packages
            </Typography>
            <List dense>
              {result.packages.map((pkg, index) => (
                <ListItem key={index} divider>
                  <ListItemText
                    primary={pkg.name || pkg.fileName || `Package ${index + 1}`}
                    secondary={
                      <Box>
                        <Chip
                          label={pkg.status || 'Generated'}
                          size="small"
                          color={pkg.status === 'FAILED' ? 'error' : 'success'}
                        />
                        {pkg.centreCode && (
                          <Chip
                            label={pkg.centreCode}
                            size="small"
                            variant="outlined"
                            sx={{ ml: 1 }}
                          />
                        )}
                      </Box>
                    }
                  />
                </ListItem>
              ))}
            </List>
          </Box>
        )}
      </DialogContent>

      <DialogActions sx={{ flexWrap: 'wrap', gap: 1 }}>
        <Button onClick={onClose}>
          Close
        </Button>
        {isSuccess && (
          <>
            <Button
              variant="outlined"
              startIcon={<DownloadIcon />}
              onClick={onViewPackages}
            >
              View Packages
            </Button>
            <Button
              variant="outlined"
              startIcon={<HistoryIcon />}
              onClick={onViewHistory}
            >
              View History
            </Button>
            <Button
              variant="contained"
              color="primary"
              startIcon={<DashboardIcon />}
              onClick={onGoToDashboard}
            >
              Go to Dashboard
            </Button>
          </>
        )}
      </DialogActions>
    </Dialog>
  );
};

export default GenerationResultDialog;