/**
 * Recent Packages Table Component
 * 
 * Displays recently generated packages with actions
 * 
 * Props:
 * - data: Recent packages data
 * - loading: Loading state
 * - error: Error state
 * - onView: View action handler
 * - onValidate: Validate action handler
 * - onDistribution: Distribution handler
 * - onVersions: Versions handler
 * - onHistory: History handler
 * - onDownload: Download handler
 * 
 * Location: src/components/packages/RecentPackagesTable.jsx
 */

import {
  Card,
  CardContent,
  CardHeader,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Chip,
  IconButton,
  Tooltip,
  Box,
  Typography,
  Skeleton,
  Avatar,
} from '@mui/material';
import {
  Visibility as ViewIcon,
  Verified as ValidateIcon,
  CloudUpload as DistributeIcon,
  Timeline as VersionsIcon,
  History as HistoryIcon,
  Download as DownloadIcon,
} from '@mui/icons-material';
import { useTheme } from '@mui/material/styles';
import dayjs from 'dayjs';
import PackageStatusChip from '../packages/PackageStatusChip';

const RecentPackagesTable = ({
  data = [],
  loading,
  error,
  onView,
  onValidate,
  onDistribution,
  onVersions,
  onHistory,
  onDownload,
}) => {
  const theme = useTheme();

  if (loading) {
    return (
      <Card>
        <CardHeader title="Recent Packages" />
        <CardContent>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
            {[1, 2, 3, 4, 5].map((i) => (
              <Skeleton key={i} variant="rectangular" height={40} />
            ))}
          </Box>
        </CardContent>
      </Card>
    );
  }

  if (error) {
    return (
      <Card>
        <CardHeader title="Recent Packages" />
        <CardContent>
          <Typography color="error">Failed to load recent packages</Typography>
        </CardContent>
      </Card>
    );
  }

  if (data.length === 0) {
    return (
      <Card>
        <CardHeader title="Recent Packages" />
        <CardContent>
          <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: 200 }}>
            <Typography color="text.secondary">No packages generated yet</Typography>
          </Box>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader
        title="Recent Packages"
        subheader={`${data.length} most recent packages`}
      />
      <CardContent sx={{ p: 0 }}>
        <TableContainer>
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell>Package</TableCell>
                <TableCell>Examination</TableCell>
                <TableCell>Centre</TableCell>
                <TableCell>Version</TableCell>
                <TableCell>Status</TableCell>
                <TableCell>Generated By</TableCell>
                <TableCell>Generated Date</TableCell>
                <TableCell align="right">Actions</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {data.map((pkg) => (
                <TableRow key={pkg._id} hover>
                  <TableCell>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                      <Avatar sx={{ width: 24, height: 24, fontSize: 12, bgcolor: theme.palette.primary.light }}>
                        {pkg.packageCode?.charAt(0) || 'P'}
                      </Avatar>
                      <Typography variant="body2" fontWeight="medium">
                        {pkg.packageCode}
                      </Typography>
                    </Box>
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2" noWrap sx={{ maxWidth: 120 }}>
                      {pkg.examName || pkg.examCode || 'Unknown'}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2">
                      {pkg.centreName || pkg.centreCode || 'Unknown'}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Chip
                      size="small"
                      label={`V${pkg.packageVersion || 1}`}
                      variant="outlined"
                      sx={{ fontSize: '0.7rem' }}
                    />
                  </TableCell>
                  <TableCell>
                    <PackageStatusChip status={pkg.status} size="small" />
                  </TableCell>
                  <TableCell>
                    <Typography variant="caption">
                      {pkg.generatedBy?.name || 'System'}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Typography variant="caption">
                      {dayjs(pkg.generatedAt || pkg.createdAt).format('DD MMM YYYY')}
                    </Typography>
                  </TableCell>
                  <TableCell align="right">
                    <Box sx={{ display: 'flex', gap: 0.5, justifyContent: 'flex-end' }}>
                      <Tooltip title="View">
                        <IconButton size="small" onClick={() => onView?.(pkg._id)}>
                          <ViewIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                      <Tooltip title="Validate">
                        <IconButton size="small" onClick={() => onValidate?.(pkg._id)} color="success">
                          <ValidateIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                      <Tooltip title="Distribution">
                        <IconButton size="small" onClick={() => onDistribution?.(pkg._id)} color="primary">
                          <DistributeIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                      <Tooltip title="Versions">
                        <IconButton size="small" onClick={() => onVersions?.(pkg._id)}>
                          <VersionsIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                      <Tooltip title="History">
                        <IconButton size="small" onClick={() => onHistory?.(pkg._id)}>
                          <HistoryIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                      {pkg.status === 'VALIDATED' && (
                        <Tooltip title="Download">
                          <IconButton size="small" onClick={() => onDownload?.(pkg._id)} color="secondary">
                            <DownloadIcon fontSize="small" />
                          </IconButton>
                        </Tooltip>
                      )}
                    </Box>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </CardContent>
    </Card>
  );
};

export default RecentPackagesTable;