/**
 * Permissions Constants
 * System permission definitions
 */

export const PERMISSIONS = {
  // Categories
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  VIEW_CATEGORY: 'VIEW_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  MANAGE_CATEGORY_STATUS: 'MANAGE_CATEGORY_STATUS',

  // Subjects
  CREATE_SUBJECT: 'CREATE_SUBJECT',
  VIEW_SUBJECT: 'VIEW_SUBJECT',
  UPDATE_SUBJECT: 'UPDATE_SUBJECT',
  DELETE_SUBJECT: 'DELETE_SUBJECT',
  MANAGE_SUBJECT_STATUS: 'MANAGE_SUBJECT_STATUS',

  // Topics
  CREATE_TOPIC: 'CREATE_TOPIC',
  VIEW_TOPIC: 'VIEW_TOPIC',
  UPDATE_TOPIC: 'UPDATE_TOPIC',
  DELETE_TOPIC: 'DELETE_TOPIC',
  MANAGE_TOPIC_STATUS: 'MANAGE_TOPIC_STATUS',

  // Questions
  CREATE_QUESTION: 'CREATE_QUESTION',
  VIEW_QUESTION: 'VIEW_QUESTION',
  UPDATE_QUESTION: 'UPDATE_QUESTION',
  DELETE_QUESTION: 'DELETE_QUESTION',
  SUBMIT_QUESTION: 'SUBMIT_QUESTION',
  PUBLISH_QUESTION: 'PUBLISH_QUESTION',
  REVIEW_QUESTION: 'REVIEW_QUESTION',

  // Media
  UPLOAD_MEDIA: 'UPLOAD_MEDIA',
  VIEW_MEDIA: 'VIEW_MEDIA',
  UPDATE_MEDIA: 'UPDATE_MEDIA',
  DELETE_MEDIA: 'DELETE_MEDIA',

  // Import
  UPLOAD_IMPORT: 'UPLOAD_IMPORT',
  VALIDATE_IMPORT: 'VALIDATE_IMPORT',
  PROCESS_IMPORT: 'PROCESS_IMPORT',
  VIEW_IMPORT_REPORT: 'VIEW_IMPORT_REPORT',

  // Users
  VIEW_USERS: 'VIEW_USERS',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',

  // Settings
  VIEW_SETTINGS: 'VIEW_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  RESET_SETTINGS: 'RESET_SETTINGS',

  // Audit
  VIEW_AUDIT: 'VIEW_AUDIT',
  VIEW_AUDIT_STATISTICS: 'VIEW_AUDIT_STATISTICS',

  // Dashboard
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_STATISTICS: 'VIEW_STATISTICS',
};

export default PERMISSIONS;