/**
 * RegeneratePackageDialog Component
 * Dialog for regenerating a package version
 * 
 * Location: src/components/packageVersions/RegeneratePackageDialog.jsx
 */

import { useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Box,
  Typography,
  Button,
  TextField,
  Alert,
  CircularProgress,
  IconButton,
  Grid,
  Paper,
  Chip,
  Divider
} from '@mui/material';
import {
  Close as CloseIcon,
  Refresh as RefreshIcon,
  Warning as WarningIcon,
  Info as InfoIcon,
  CheckCircle as CheckIcon
} from '@mui/icons-material';

const RegeneratePackageDialog = ({
  open,
  onClose,
  onConfirm,
  version,
  loading = false
}) => {
  const [reason, setReason] = useState('');
  const [notes, setNotes] = useState('');
  const [errors, setErrors] = useState({});

  const validate = () => {
    const newErrors = {};
    
    if (!reason.trim()) {
      newErrors.reason = 'Reason is required';
    }
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleConfirm = () => {
    if (validate()) {
      onConfirm({
        reason: reason.trim(),
        notes: notes.trim()
      });
    }
  };

  const handleClose = () => {
    setReason('');
    setNotes('');
    setErrors({});
    onClose();
  };

  if (!version) {
    return (
      <Dialog open={open} onClose={handleClose} maxWidth="sm" fullWidth>
        <DialogTitle>Regenerate Package</DialogTitle>
        <DialogContent>
          <Alert severity="warning">No version selected for regeneration</Alert>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleClose}>Close</Button>
        </DialogActions>
      </Dialog>
    );
  }

  const versionNumber = version.versionNumber || version.version || 1;
  const packageName = version.packageName || version.package?.name || 'Package';

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      maxWidth="md"
      fullWidth
    >
      <DialogTitle>
        <Box display="flex" justifyContent="space-between" alignItems="center">
          <Box display="flex" alignItems="center" gap={1}>
            <RefreshIcon color="warning" />
            <Typography variant="h6">Regenerate Package</Typography>
          </Box>
          <IconButton onClick={handleClose} size="small">
            <CloseIcon />
          </IconButton>
        </Box>
      </DialogTitle>

      <DialogContent dividers>
        {/* Warning Alert */}
        <Alert severity="warning" sx={{ mb: 2 }}>
          <Typography variant="subtitle2">You are about to regenerate this package</Typography>
          <Typography variant="body2">
            This will create a new version while preserving all previous versions. 
            The new version will become the active version.
          </Typography>
        </Alert>

        {/* Package Information */}
        <Paper variant="outlined" sx={{ p: 2, mb: 2 }}>
          <Typography variant="subtitle2" gutterBottom>
            Package Information
          </Typography>
          <Grid container spacing={2}>
            <Grid item xs={6}>
              <Typography variant="caption" color="text.secondary">
                Package Name
              </Typography>
              <Typography variant="body2" fontWeight={500}>
                {packageName}
              </Typography>
            </Grid>
            <Grid item xs={6}>
              <Typography variant="caption" color="text.secondary">
                Current Version
              </Typography>
              <Typography variant="body2">
                V{versionNumber}
                {version.isLatest && (
                  <Chip label="Latest" size="small" color="success" sx={{ ml: 1 }} />
                )}
              </Typography>
            </Grid>
            <Grid item xs={6}>
              <Typography variant="caption" color="text.secondary">
                Centre
              </Typography>
              <Typography variant="body2">
                {version.centre?.name || version.centreName || 'N/A'}
              </Typography>
            </Grid>
            <Grid item xs={6}>
              <Typography variant="caption" color="text.secondary">
                Status
              </Typography>
              <Chip
                label={version.status || 'Active'}
                color={version.status === 'ACTIVE' ? 'success' : 'default'}
                size="small"
              />
            </Grid>
            <Grid item xs={6}>
              <Typography variant="caption" color="text.secondary">
                Generated By
              </Typography>
              <Typography variant="body2">
                {version.generatedBy?.name || version.generatedBy || 'System'}
              </Typography>
            </Grid>
            <Grid item xs={6}>
              <Typography variant="caption" color="text.secondary">
                Generated Date
              </Typography>
              <Typography variant="body2">
                {new Date(version.generatedAt || version.createdAt).toLocaleDateString()}
              </Typography>
            </Grid>
          </Grid>
        </Paper>

        {/* What will happen */}
        <Box sx={{ mb: 2 }}>
          <Typography variant="subtitle2" gutterBottom>
            What will happen?
          </Typography>
          <Grid container spacing={1}>
            <Grid item xs={12}>
              <Box display="flex" alignItems="center" gap={1}>
                <CheckIcon color="success" fontSize="small" />
                <Typography variant="body2">
                  A new version (V{versionNumber + 1}) will be created
                </Typography>
              </Box>
            </Grid>
            <Grid item xs={12}>
              <Box display="flex" alignItems="center" gap={1}>
                <CheckIcon color="success" fontSize="small" />
                <Typography variant="body2">
                  All previous versions will be preserved
                </Typography>
              </Box>
            </Grid>
            <Grid item xs={12}>
              <Box display="flex" alignItems="center" gap={1}>
                <CheckIcon color="success" fontSize="small" />
                <Typography variant="body2">
                  The new version will become the active version
                </Typography>
              </Box>
            </Grid>
            <Grid item xs={12}>
              <Box display="flex" alignItems="center" gap={1}>
                <WarningIcon color="warning" fontSize="small" />
                <Typography variant="body2" color="warning.main">
                  Current version will be marked as superseded
                </Typography>
              </Box>
            </Grid>
          </Grid>
        </Box>

        <Divider sx={{ mb: 2 }} />

        {/* Regeneration Details */}
        <Box>
          <Typography variant="subtitle2" gutterBottom>
            Regeneration Details
          </Typography>
          
          <TextField
            fullWidth
            required
            multiline
            rows={2}
            label="Reason for Regeneration"
            placeholder="Please provide a reason for regenerating this package..."
            value={reason}
            onChange={(e) => setReason(e.target.value)}
            error={!!errors.reason}
            helperText={errors.reason}
            sx={{ mb: 2 }}
          />

          <TextField
            fullWidth
            multiline
            rows={2}
            label="Additional Notes (Optional)"
            placeholder="Add any additional notes about this regeneration..."
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
          />
        </Box>

        {/* Confirmation */}
        <Alert severity="info" sx={{ mt: 2 }}>
          <Box display="flex" alignItems="center" gap={1}>
            <InfoIcon />
            <Typography variant="body2">
              This action will regenerate the package and all associated candidate papers.
              The process may take a few minutes.
            </Typography>
          </Box>
        </Alert>
      </DialogContent>

      <DialogActions sx={{ p: 2, gap: 1 }}>
        <Button onClick={handleClose} disabled={loading}>
          Cancel
        </Button>
        <Button
          onClick={handleConfirm}
          variant="contained"
          color="warning"
          disabled={loading || !reason.trim()}
          startIcon={loading ? <CircularProgress size={20} /> : <RefreshIcon />}
        >
          {loading ? 'Regenerating...' : 'Regenerate Package'}
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default RegeneratePackageDialog;