/* eslint-disable no-unused-vars */
/**
 * VersionTable Component
 * Displays versions in a data grid
 * 
 * Location: src/components/packageVersions/VersionTable.jsx
 */

import {
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
  IconButton,
  Tooltip,
  Box,
  Typography,
  Skeleton
} from '@mui/material';
import {
  Visibility as ViewIcon,
  CompareArrows as CompareIcon,
  Refresh as RegenerateIcon,
  Timeline as TimelineIcon,
  Archive as ArchiveIcon,
  History as HistoryIcon
} from '@mui/icons-material';
import VersionStatusChip from './VersionStatusChip';

const VersionTable = ({
  versions,
  total,
  page,
  limit,
  loading = false,
  onPageChange,
  onRowsPerPageChange,
  onViewDetails,
  onCompare,
  onRegenerate,
  onViewTimeline,
  onArchive,
  canRegenerate = false,
  canArchive = false
}) => {
  const handlePageChange = (event, newPage) => {
    onPageChange(event, newPage);
  };

  const handleRowsPerPageChange = (event) => {
    onRowsPerPageChange(event);
  };

  // Skeleton rows for loading state
  if (loading) {
    return (
      <Paper>
        <TableContainer>
          <Table>
            <TableHead>
              <TableRow>
                {['Package', 'Version', 'Examination', 'Centre', 'Status', 'Generated By', 'Date', 'Actions'].map((col) => (
                  <TableCell key={col}>{col}</TableCell>
                ))}
              </TableRow>
            </TableHead>
            <TableBody>
              {[...Array(5)].map((_, i) => (
                <TableRow key={i}>
                  {[...Array(8)].map((_, j) => (
                    <TableCell key={j}>
                      <Skeleton variant="text" width={j === 7 ? 120 : 80} />
                    </TableCell>
                  ))}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </Paper>
    );
  }

  // Empty state
  if (versions.length === 0) {
    return (
      <Paper sx={{ p: 4, textAlign: 'center' }}>
        <Typography variant="body1" color="text.secondary">
          No versions found
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
          Try adjusting your filters or generate a package version
        </Typography>
      </Paper>
    );
  }

  const isActive = (status) => status === 'ACTIVE';
  const isArchived = (status) => status === 'ARCHIVED';

  return (
    <Paper>
      <TableContainer>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>Package</TableCell>
              <TableCell>Version</TableCell>
              <TableCell>Examination</TableCell>
              <TableCell>Centre</TableCell>
              <TableCell>Status</TableCell>
              <TableCell>Generated By</TableCell>
              <TableCell>Date</TableCell>
              <TableCell align="center">Actions</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {versions.map((version) => (
              <TableRow key={version._id} hover>
                <TableCell>
                  <Typography variant="body2" fontWeight={500}>
                    {version.packageName || version.package?.name || 'N/A'}
                  </Typography>
                </TableCell>
                <TableCell>
                  <Typography variant="body2">
                    V{version.versionNumber || version.version || 1}
                  </Typography>
                  {version.isLatest && (
                    <Typography variant="caption" color="success.main">
                      (Latest)
                    </Typography>
                  )}
                </TableCell>
                <TableCell>
                  <Box>
                    <Typography variant="body2">
                      {version.examination?.name || version.examName || 'N/A'}
                    </Typography>
                    <Typography variant="caption" color="text.secondary">
                      {version.examCode || ''}
                    </Typography>
                  </Box>
                </TableCell>
                <TableCell>
                  <Typography variant="body2">
                    {version.centre?.name || version.centreName || 'N/A'}
                  </Typography>
                </TableCell>
                <TableCell>
                  <VersionStatusChip status={version.status} size="small" />
                </TableCell>
                <TableCell>
                  <Typography variant="body2">
                    {version.generatedBy?.name || version.generatedBy || 'System'}
                  </Typography>
                </TableCell>
                <TableCell>
                  <Typography variant="body2">
                    {new Date(version.generatedAt || version.createdAt).toLocaleDateString()}
                  </Typography>
                  <Typography variant="caption" color="text.secondary">
                    {new Date(version.generatedAt || version.createdAt).toLocaleTimeString()}
                  </Typography>
                </TableCell>
                <TableCell align="center">
                  <Box display="flex" justifyContent="center" gap={0.5}>
                    {/* View Details */}
                    <Tooltip title="View Details">
                      <IconButton
                        size="small"
                        onClick={() => onViewDetails(version._id)}
                      >
                        <ViewIcon fontSize="small" />
                      </IconButton>
                    </Tooltip>

                    {/* Compare Version */}
                    <Tooltip title="Compare Version">
                      <IconButton
                        size="small"
                        color="secondary"
                        onClick={() => onCompare(version._id)}
                      >
                        <CompareIcon fontSize="small" />
                      </IconButton>
                    </Tooltip>

                    {/* Regenerate */}
                    {canRegenerate && isActive(version.status) && (
                      <Tooltip title="Regenerate">
                        <IconButton
                          size="small"
                          color="primary"
                          onClick={() => onRegenerate(version._id)}
                        >
                          <RegenerateIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                    )}

                    {/* View Timeline */}
                    <Tooltip title="View Timeline">
                      <IconButton
                        size="small"
                        onClick={() => onViewTimeline(version._id)}
                      >
                        <TimelineIcon fontSize="small" />
                      </IconButton>
                    </Tooltip>

                    {/* Archive */}
                    {canArchive && !isArchived(version.status) && (
                      <Tooltip title="Archive">
                        <IconButton
                          size="small"
                          color="error"
                          onClick={() => onArchive(version._id)}
                        >
                          <ArchiveIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                    )}
                  </Box>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
      <TablePagination
        component="div"
        count={total}
        page={page - 1}
        rowsPerPage={limit}
        onPageChange={handlePageChange}
        onRowsPerPageChange={handleRowsPerPageChange}
        rowsPerPageOptions={[10, 20, 50, 100]}
        labelRowsPerPage="Rows per page:"
      />
    </Paper>
  );
};

export default VersionTable;